#!/usr/bin/env python3
from __future__ import annotations

import argparse
import copy
import json
import time
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple

VALID_JUDGE_LABELS = {"keep", "reject", "repair"}


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Build baseline / auto_correction / human_override snapshots from "
            "a stability report and validate the correction flow."
        )
    )
    parser.add_argument(
        "--report",
        required=True,
        help="Path to the report.json generated by scripts/demo/stability_eval.py.",
    )
    parser.add_argument(
        "--output-dir",
        default="scripts/demo/results/correction",
        help="Directory for baseline/auto/human snapshots and selfcheck summary.",
    )
    parser.add_argument(
        "--run-name",
        default=None,
        help="Optional run name. Defaults to a timestamp.",
    )
    parser.add_argument(
        "--overrides",
        default=None,
        help="Optional JSONL file with concept-level human overrides.",
    )
    return parser


def write_json(path: Path, payload: Dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def write_jsonl(path: Path, rows: Sequence[Dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [json.dumps(row, ensure_ascii=False) for row in rows]
    path.write_text("\n".join(lines) + ("\n" if lines else ""), encoding="utf-8")


def load_json(path: Path) -> Dict[str, Any]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError(f"{path} must contain a top-level JSON object.")
    return payload


def load_jsonl(path: Path) -> List[Dict[str, Any]]:
    rows: List[Dict[str, Any]] = []
    for line_no, raw_line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
        line = raw_line.strip()
        if not line:
            continue
        row = json.loads(line)
        if not isinstance(row, dict):
            raise ValueError(f"{path}:{line_no} must be a JSON object.")
        rows.append(row)
    return rows


def make_run_dir(base_dir: Path, run_name: Optional[str]) -> Path:
    stamp = time.strftime("%Y%m%d_%H%M%S")
    run_dir = base_dir / (run_name or stamp)
    run_dir.mkdir(parents=True, exist_ok=True)
    return run_dir


def normalize_text(text: Any) -> str:
    return " ".join(str(text or "").strip().lower().split())


def normalize_span(span: Any) -> Optional[List[int]]:
    if not isinstance(span, (list, tuple)) or len(span) != 2:
        return None
    try:
        start = int(span[0])
        end = int(span[1])
    except (TypeError, ValueError):
        return None
    if end <= start:
        return None
    return [start, end]


def normalize_bbox(bbox: Any) -> Optional[List[float]]:
    if not isinstance(bbox, (list, tuple)) or len(bbox) != 4:
        return None
    try:
        x1, y1, x2, y2 = [float(value) for value in bbox]
    except (TypeError, ValueError):
        return None
    if x2 <= x1 or y2 <= y1:
        return None
    return [x1, y1, x2, y2]


def spans_overlap(span_a: Optional[List[int]], span_b: Optional[List[int]]) -> bool:
    if not span_a or not span_b:
        return False
    return not (span_a[1] <= span_b[0] or span_b[1] <= span_a[0])


def choose_answer_span(phrase: Dict[str, Any]) -> Optional[List[int]]:
    return (
        normalize_span(phrase.get("concept_char_span"))
        or normalize_span(phrase.get("mention_char_span"))
        or normalize_span(phrase.get("char_span"))
    )


def match_ground_records(
    phrases: Sequence[Dict[str, Any]],
    ground_records: Sequence[Dict[str, Any]],
) -> Dict[int, Dict[str, Any]]:
    matched: Dict[int, Dict[str, Any]] = {}
    used_records: set[int] = set()
    for phrase_idx, phrase in enumerate(phrases):
        phrase_text = normalize_text(phrase.get("mention_text") or phrase.get("text"))
        phrase_span = choose_answer_span(phrase) or normalize_span(phrase.get("char_span"))
        best_record_idx = None
        best_score = -1
        for record_idx, record in enumerate(ground_records):
            if record_idx in used_records:
                continue
            score = 0
            record_text = normalize_text(record.get("phrase"))
            record_span = normalize_span(record.get("char_span"))
            if phrase_span and record_span and phrase_span == record_span:
                score += 4
            elif spans_overlap(phrase_span, record_span):
                score += 1
            if phrase_text and phrase_text == record_text:
                score += 2
            elif phrase_text and record_text and phrase_text in record_text:
                score += 1
            if score > best_score:
                best_record_idx = record_idx
                best_score = score
        if best_record_idx is not None and best_score > 0:
            matched[phrase_idx] = ground_records[best_record_idx]
            used_records.add(best_record_idx)
    return matched


def baseline_decision(
    phrase: Dict[str, Any],
    record: Optional[Dict[str, Any]],
) -> Tuple[str, str]:
    concept_text = normalize_text(phrase.get("concept_text"))
    bbox = normalize_bbox((record or {}).get("bbox"))
    if not bbox:
        return "reject", "ground_missing"
    if not concept_text:
        return "repair", "concept_unresolved"
    return "keep", "grounded_concept_available"


def auto_decision(
    concept_row: Dict[str, Any],
    sample_tags: Iterable[str],
) -> Tuple[str, str, Dict[str, Any], List[str]]:
    tags = list(sample_tags)
    bbox = normalize_bbox(concept_row.get("roi_bbox"))
    mention_text = normalize_text(concept_row.get("mention_text"))
    concept_text = normalize_text(concept_row.get("concept_text"))
    corrected: Dict[str, Any] = {}
    review_flags: List[str] = list(tags)

    if not bbox:
        return "reject", "ground_missing", corrected, review_flags
    if concept_text and concept_text != mention_text:
        corrected["corrected_concept_text"] = concept_row.get("concept_text")
        corrected["corrected_answer_span"] = concept_row.get("concept_answer_span")
        return "repair", "normalize_mention_to_concept", corrected, review_flags
    if "answer_decoding_artifact" in tags:
        review_flags.append("needs_answer_cleanup")
    return "keep", "auto_keep", corrected, review_flags


def build_concept_rows(sample: Dict[str, Any]) -> List[Dict[str, Any]]:
    phrases = list(sample.get("phrases") or [])
    ground_records = list(sample.get("ground_records") or [])
    matched_records = match_ground_records(phrases, ground_records)
    rows: List[Dict[str, Any]] = []
    for phrase_idx, phrase in enumerate(phrases):
        record = matched_records.get(phrase_idx)
        mention_text = phrase.get("mention_text") or phrase.get("text") or ""
        baseline_label, baseline_reason = baseline_decision(phrase, record)
        row = {
            "concept_id": f"{sample['sample_id']}:concept:{phrase_idx}",
            "phrase_index": phrase_idx,
            "record_index": (record or {}).get("index"),
            "mention_text": mention_text,
            "mention_answer_span": normalize_span(
                phrase.get("mention_char_span") or phrase.get("char_span")
            ),
            "mention_token_span": normalize_span(
                phrase.get("mention_token_span") or phrase.get("token_span")
            ),
            "concept_text": phrase.get("concept_text"),
            "concept_answer_span": normalize_span(phrase.get("concept_char_span")),
            "concept_token_span": normalize_span(phrase.get("concept_token_span")),
            "concept_lemma": phrase.get("concept_lemma"),
            "concept_source": phrase.get("concept_source"),
            "answer_span": choose_answer_span(phrase),
            "roi_bbox": normalize_bbox((record or {}).get("bbox")),
            "overlay_path": (record or {}).get("overlay_path"),
            "mask_path": (record or {}).get("mask_path"),
            "roi_path": (record or {}).get("roi_path"),
            "judge_label": baseline_label,
            "judge_reason": baseline_reason,
            "judge_source": "baseline",
            "corrected_concept_text": None,
            "corrected_answer_span": None,
            "corrected_bbox": None,
            "review_flags": [],
        }
        rows.append(row)
    return rows


def build_snapshot(
    report: Dict[str, Any],
    *,
    mode: str,
    source_report: Path,
    concept_transform,
) -> Dict[str, Any]:
    samples_payload: List[Dict[str, Any]] = []
    for sample in report.get("samples", []):
        concept_rows = build_concept_rows(sample)
        transformed_rows = [concept_transform(row, sample) for row in concept_rows]
        samples_payload.append(
            {
                "sample_id": sample.get("sample_id"),
                "source_id": sample.get("source_id"),
                "status": sample.get("status"),
                "question": sample.get("question"),
                "notes": sample.get("notes", ""),
                "answers": {
                    "raw_answer": sample.get("raw_answer"),
                    "final_answer": sample.get("answer"),
                    "roi_answer": sample.get("roi_answer"),
                },
                "auto_failure_tags": list(sample.get("auto_failure_tags") or []),
                "manual_failure_tags": list(sample.get("manual_failure_tags") or []),
                "concept_records": transformed_rows,
                "error": sample.get("error"),
            }
        )
    return {
        "schema_version": "correction_snapshot_v1",
        "mode": mode,
        "created_at": time.strftime("%Y-%m-%d %H:%M:%S"),
        "source_report": str(source_report),
        "source_manifest": (report.get("summary") or {}).get("manifest_path"),
        "samples": samples_payload,
    }


def baseline_transform(row: Dict[str, Any], sample: Dict[str, Any]) -> Dict[str, Any]:
    del sample
    return row


def auto_transform(row: Dict[str, Any], sample: Dict[str, Any]) -> Dict[str, Any]:
    updated = copy.deepcopy(row)
    label, reason, corrected, review_flags = auto_decision(
        updated,
        sample.get("auto_failure_tags") or [],
    )
    updated["judge_label"] = label
    updated["judge_reason"] = reason
    updated["judge_source"] = "auto"
    updated["review_flags"] = review_flags
    for key, value in corrected.items():
        updated[key] = value
    return updated


def build_override_template(auto_snapshot: Dict[str, Any]) -> List[Dict[str, Any]]:
    template_rows: List[Dict[str, Any]] = []
    for sample in auto_snapshot.get("samples", []):
        for concept in sample.get("concept_records", []):
            template_rows.append(
                {
                    "schema_version": "correction_override_v1",
                    "sample_id": sample.get("sample_id"),
                    "concept_id": concept.get("concept_id"),
                    "question": sample.get("question"),
                    "mention_text": concept.get("mention_text"),
                    "concept_text": concept.get("concept_text"),
                    "answer_span": concept.get("answer_span"),
                    "roi_bbox": concept.get("roi_bbox"),
                    "judge_label": "",
                    "judge_reason": "",
                    "corrected_concept_text": "",
                    "corrected_answer_span": [],
                    "corrected_bbox": [],
                    "comment": "",
                }
            )
    return template_rows


def has_override_payload(row: Dict[str, Any]) -> bool:
    editable_values = [
        row.get("judge_label"),
        row.get("judge_reason"),
        row.get("corrected_concept_text"),
        row.get("corrected_answer_span"),
        row.get("corrected_bbox"),
        row.get("comment"),
    ]
    for value in editable_values:
        if isinstance(value, str) and value.strip():
            return True
        if isinstance(value, list) and value:
            return True
    return False


def apply_human_overrides(
    auto_snapshot: Dict[str, Any],
    overrides: Sequence[Dict[str, Any]],
) -> Tuple[Dict[str, Any], List[Dict[str, Any]]]:
    merged = copy.deepcopy(auto_snapshot)
    merged["mode"] = "human_override"
    index: Dict[Tuple[str, str], Dict[str, Any]] = {}
    for sample in merged.get("samples", []):
        for concept in sample.get("concept_records", []):
            key = (str(sample.get("sample_id")), str(concept.get("concept_id")))
            index[key] = concept

    errors: List[Dict[str, Any]] = []
    for row in overrides:
        if not has_override_payload(row):
            continue
        sample_id = str(row.get("sample_id") or "")
        concept_id = str(row.get("concept_id") or "")
        target = index.get((sample_id, concept_id))
        if target is None:
            errors.append(
                {
                    "type": "unknown_concept",
                    "sample_id": sample_id,
                    "concept_id": concept_id,
                }
            )
            continue

        judge_label = str(row.get("judge_label") or "").strip().lower()
        if judge_label not in VALID_JUDGE_LABELS:
            errors.append(
                {
                    "type": "invalid_judge_label",
                    "sample_id": sample_id,
                    "concept_id": concept_id,
                    "judge_label": row.get("judge_label"),
                }
            )
            continue

        target["judge_label"] = judge_label
        target["judge_reason"] = str(row.get("judge_reason") or "").strip() or "human_override"
        target["judge_source"] = "human"
        corrected_concept_text = str(row.get("corrected_concept_text") or "").strip()
        target["corrected_concept_text"] = corrected_concept_text or None
        target["corrected_answer_span"] = normalize_span(row.get("corrected_answer_span"))
        target["corrected_bbox"] = normalize_bbox(row.get("corrected_bbox"))
        target["human_comment"] = str(row.get("comment") or "").strip()
    return merged, errors


def validate_snapshot(
    snapshot: Dict[str, Any],
    *,
    override_errors: Optional[Sequence[Dict[str, Any]]] = None,
) -> Dict[str, Any]:
    judge_counts = {label: 0 for label in sorted(VALID_JUDGE_LABELS)}
    failure_counts = {
        "detection_failure": 0,
        "judgment_failure": 0,
        "repair_failure": 0,
        "human_override_failure": len(list(override_errors or [])),
    }
    issues: List[Dict[str, Any]] = list(override_errors or [])
    concept_total = 0
    bbox_total = 0

    for sample in snapshot.get("samples", []):
        for concept in sample.get("concept_records", []):
            concept_total += 1
            concept_id = concept.get("concept_id")
            judge_label = str(concept.get("judge_label") or "").strip().lower()
            answer_span = normalize_span(concept.get("answer_span"))
            roi_bbox = normalize_bbox(concept.get("roi_bbox"))
            if roi_bbox:
                bbox_total += 1
            else:
                failure_counts["detection_failure"] += 1
                issues.append(
                    {
                        "type": "missing_roi_bbox",
                        "sample_id": sample.get("sample_id"),
                        "concept_id": concept_id,
                    }
                )
            if answer_span is None:
                failure_counts["judgment_failure"] += 1
                issues.append(
                    {
                        "type": "missing_answer_span",
                        "sample_id": sample.get("sample_id"),
                        "concept_id": concept_id,
                    }
                )
            if judge_label not in VALID_JUDGE_LABELS:
                failure_counts["judgment_failure"] += 1
                issues.append(
                    {
                        "type": "invalid_judge_label",
                        "sample_id": sample.get("sample_id"),
                        "concept_id": concept_id,
                        "judge_label": concept.get("judge_label"),
                    }
                )
                continue
            judge_counts[judge_label] += 1
            if judge_label == "repair":
                has_correction = any(
                    [
                        str(concept.get("corrected_concept_text") or "").strip(),
                        normalize_span(concept.get("corrected_answer_span")),
                        normalize_bbox(concept.get("corrected_bbox")),
                    ]
                )
                if not has_correction:
                    failure_counts["repair_failure"] += 1
                    issues.append(
                        {
                            "type": "repair_without_payload",
                            "sample_id": sample.get("sample_id"),
                            "concept_id": concept_id,
                        }
                    )

    return {
        "mode": snapshot.get("mode"),
        "num_samples": len(snapshot.get("samples", [])),
        "num_concepts": concept_total,
        "num_with_roi_bbox": bbox_total,
        "judge_counts": judge_counts,
        "failure_counts": failure_counts,
        "issues": issues,
    }


def build_all_snapshots(
    report: Dict[str, Any],
    report_path: Path,
    overrides: Optional[Sequence[Dict[str, Any]]] = None,
) -> Tuple[Dict[str, Any], Dict[str, Any], Optional[Dict[str, Any]], List[Dict[str, Any]]]:
    baseline = build_snapshot(
        report,
        mode="baseline",
        source_report=report_path,
        concept_transform=baseline_transform,
    )
    auto_snapshot = build_snapshot(
        report,
        mode="auto_correction",
        source_report=report_path,
        concept_transform=auto_transform,
    )
    human_snapshot = None
    override_errors: List[Dict[str, Any]] = []
    if overrides is not None:
        human_snapshot, override_errors = apply_human_overrides(auto_snapshot, overrides)
    return baseline, auto_snapshot, human_snapshot, override_errors


def main() -> None:
    args = build_parser().parse_args()
    report_path = Path(args.report).expanduser().resolve()
    report = load_json(report_path)
    overrides = None
    if args.overrides:
        overrides = load_jsonl(Path(args.overrides).expanduser().resolve())

    run_dir = make_run_dir(Path(args.output_dir).expanduser().resolve(), args.run_name)
    baseline, auto_snapshot, human_snapshot, override_errors = build_all_snapshots(
        report,
        report_path,
        overrides=overrides,
    )

    baseline_path = run_dir / "baseline.json"
    auto_path = run_dir / "auto_correction.json"
    template_path = run_dir / "human_override.template.jsonl"
    write_json(baseline_path, baseline)
    write_json(auto_path, auto_snapshot)
    write_jsonl(template_path, build_override_template(auto_snapshot))

    selfcheck = {
        "schema_version": "correction_selfcheck_v1",
        "created_at": time.strftime("%Y-%m-%d %H:%M:%S"),
        "inputs": {
            "report": str(report_path),
            "overrides": str(Path(args.overrides).expanduser().resolve()) if args.overrides else None,
        },
        "baseline": validate_snapshot(baseline),
        "auto_correction": validate_snapshot(auto_snapshot),
        "human_override": None,
    }

    if human_snapshot is not None:
        human_path = run_dir / "human_override.json"
        write_json(human_path, human_snapshot)
        selfcheck["human_override"] = validate_snapshot(
            human_snapshot,
            override_errors=override_errors,
        )

    write_json(run_dir / "selfcheck.json", selfcheck)
    print(f"[correction-selfcheck] wrote: {baseline_path}")
    print(f"[correction-selfcheck] wrote: {auto_path}")
    print(f"[correction-selfcheck] wrote: {template_path}")
    if human_snapshot is not None:
        print(f"[correction-selfcheck] wrote: {run_dir / 'human_override.json'}")
    print(f"[correction-selfcheck] wrote: {run_dir / 'selfcheck.json'}")


if __name__ == "__main__":
    main()
